// Auto-generated by IssueOps AI bot using MCP fixtures_get
export type Team = { id: number; name: string };
export type Fixture = {
  id: number;
  date: string;
  status: string;
  home: Team;
  away: Team;
};

export type FixturesResponse = {
  leagueId: number;
  items: Fixture[];
};

export const sampleFixtures_39: FixturesResponse = {
  leagueId: 39,
  items: [
    { id: 1000, date: "2025-01-01T00:00:00Z", status: "NS", home: { id: 1, name: "Home" }, away: { id: 2, name: "Away" } },
    { id: 1001, date: "2025-01-01T00:00:00Z", status: "NS", home: { id: 1, name: "Home" }, away: { id: 2, name: "Away" } }
  ]
};
