apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
spec:
  selector: { app: {{ include "api.name" . }} }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}