name: IssueOps - AI Task
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: issueops-ai-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  ai_task:
    # IMPORTANT: job-level if must be a GitHub expression
    if: ${{ github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'ai-task') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug labels (optional)
        env:
          LABELS_JSON: "${{ toJson(github.event.issue.labels) }}"
        shell: bash
        run: |
          echo "Labels:"
          echo "$LABELS_JSON"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json  # read version from packageManager

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build MCP server
        run: pnpm -w --filter @app/mcp-football build

      - name: Prepare AI draft (stub)
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        shell: bash
        run: |
          node tools/ai/pr-bot/runner.mjs "${ISSUE_TITLE} :: ${ISSUE_BODY}"

      - name: Create draft PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "ai/issue-${{ github.event.issue.number }}"
          title: "ai: ${{ github.event.issue.title }}"
          body: |
            Drafted from Issue #${{ github.event.issue.number }}

            > ${{ github.event.issue.body }}
          draft: true
          commit-message: "ai: draft for #${{ github.event.issue.number }}"