name: PR Fast Checks (minimal)
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - name: Lint (workspace)
        run: pnpm -w lint
      - name: Typecheck (workspace)
        run: pnpm -w typecheck
      - name: Unit tests (workspace)
        run: pnpm -w test
